Remove failing line

diff --git a/.github/workflows/BTDWithChangeSNTask.yaml b/.github/workflows/BTDWithChangeSNTask.yaml
--- a/.github/workflows/BTDWithChangeSNTask.yaml
+++ b/.github/workflows/BTDWithChangeSNTask.yaml
@@ -126,6 +126,6 @@ jobs:
       - name: Run deployment scripts
         run: echo Completed Deployment.
         
-      - name: Try to Fail
-        run: exit 1
+#       - name: Try to Fail
+#         run: exit 1
       
